/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Malena Totland (https://sketchfab.com/malenatotland)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/day4-the-cottage-80929caae8da47e4adb0dbbf0275ab2f
title: DAY4: The Cottage
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cottage({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cottage.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 3.28, -2.13]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={nodes.defaultMaterial.material} />
          </group>
          <group position={[-2.57, 1.16, 1.92]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={nodes.defaultMaterial_1.material} />
          </group>
          <group position={[2.57, 1.16, -1.92]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={nodes.defaultMaterial_2.material} />
          </group>
          <group position={[-5.32, 8.22, 3.02]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={nodes.defaultMaterial_3.material} />
          </group>
          <group position={[6.83, 0.85, 2.14]} rotation={[-1.86, 0.14, -0.36]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={nodes.defaultMaterial_4.material} />
          </group>
          <group position={[6.83, 2.51, -1.28]} rotation={[-1.86, 0.14, -0.36]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={nodes.defaultMaterial_5.material} />
          </group>
          <group position={[1.36, 1.11, 6.01]} rotation={[-1.92, -0.73, 0.11]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={nodes.defaultMaterial_6.material} />
          </group>
          <group position={[6.83, 2.51, 6.01]} rotation={[-1.92, -0.73, 0.11]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={nodes.defaultMaterial_7.material} />
          </group>
          <group position={[0.19, 0.35, -3.85]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_8.geometry} material={nodes.defaultMaterial_8.material} />
          </group>
          <group position={[-6.02, 3.93, -3.85]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_9.geometry} material={nodes.defaultMaterial_9.material} />
          </group>
          <group position={[3.67, 3.93, 4.82]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_10.geometry} material={nodes.defaultMaterial_10.material} />
          </group>
          <group position={[-5.32, 5.88, 3.02]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_11.geometry} material={nodes.defaultMaterial_11.material} />
          </group>
          <group position={[-2.61, 4.14, 6.05]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_12.geometry} material={nodes.defaultMaterial_12.material} />
          </group>
          <group position={[-2.61, 4.14, -0.87]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_13.geometry} material={nodes.defaultMaterial_13.material} />
          </group>
          <group position={[2.85, 0.76, -3.2]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_14.geometry} material={nodes.defaultMaterial_14.material} />
          </group>
          <group position={[2.85, 2.09, 3.06]} rotation={[-1.97, -0.24, 0.67]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_15.geometry} material={nodes.defaultMaterial_15.material} />
          </group>
          <group position={[-2.58, 5.11, 3.06]} rotation={[-1.78, -0.08, 0.36]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_16.geometry} material={nodes.defaultMaterial_16.material} />
          </group>
          <group position={[-0.42, 3.11, 4.53]} rotation={[-1.78, -0.08, 0.36]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_17.geometry} material={nodes.defaultMaterial_17.material} />
          </group>
          <group position={[-0.42, 3.11, -4.41]} rotation={[-1.77, 0.11, -0.5]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_18.geometry} material={nodes.defaultMaterial_18.material} />
          </group>
          <group position={[-0.42, 5.64, -1.6]} rotation={[-1.76, -0.12, 0.57]} scale={[1.51, 1.51, 1.51]}>
            <mesh geometry={nodes.defaultMaterial_19.geometry} material={nodes.defaultMaterial_19.material} />
          </group>
          <group position={[4.14, 4.87, -1.6]} rotation={[-1.76, -0.12, 0.57]} scale={[2.05, 2.05, 2.05]}>
            <mesh geometry={nodes.defaultMaterial_20.geometry} material={nodes.defaultMaterial_20.material} />
          </group>
          <group position={[3.28, -0.08, 3.9]} rotation={[-Math.PI / 2, 0, -0.77]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.defaultMaterial_21.geometry} material={nodes.defaultMaterial_21.material} />
          </group>
          <group position={[3.28, 0.03, -2.51]} rotation={[-Math.PI / 2, 0, 0.55]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.defaultMaterial_22.geometry} material={nodes.defaultMaterial_22.material} />
          </group>
          <group position={[3.21, 0.03, -2.15]} rotation={[-Math.PI / 2, 0, 0.55]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.defaultMaterial_23.geometry} material={nodes.defaultMaterial_23.material} />
          </group>
          <group position={[-2.18, -0.04, -2.15]} rotation={[-Math.PI / 2, 0, 0.55]} scale={[2.05, 2.05, 2.05]}>
            <mesh geometry={nodes.defaultMaterial_24.geometry} material={nodes.defaultMaterial_24.material} />
          </group>
          <group position={[0.95, 0.06, -2.64]} rotation={[-Math.PI / 2, 0, 0.55]} scale={[2.05, 2.05, 2.05]}>
            <mesh geometry={nodes.defaultMaterial_25.geometry} material={nodes.defaultMaterial_25.material} />
          </group>
          <group position={[4.14, 0.1, -1.6]} rotation={[-Math.PI / 2, 0, 0]} scale={2.05}>
            <mesh geometry={nodes.defaultMaterial_26.geometry} material={nodes.defaultMaterial_26.material} />
          </group>
          <group position={[4.14, -0.06, 1.73]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_27.geometry} material={nodes.defaultMaterial_27.material} />
          </group>
          <group position={[0.84, 1.57, -2.09]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_28.geometry} material={nodes.defaultMaterial_28.material} />
          </group>
          <group position={[-0.86, 1.57, -2.09]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_29.geometry} material={nodes.defaultMaterial_29.material} />
          </group>
          <group position={[-0.86, 1.57, 2.06]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_30.geometry} material={nodes.defaultMaterial_30.material} />
          </group>
          <group position={[0.84, 1.57, 2.06]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_31.geometry} material={nodes.defaultMaterial_31.material} />
          </group>
          <group position={[3.84, 1.35, 1.62]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_32.geometry} material={nodes.defaultMaterial_32.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_33.geometry} material={nodes.defaultMaterial_33.material} />
          </group>
          <group position={[2, 2.77, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_34.geometry} material={nodes.defaultMaterial_34.material} />
          </group>
          <group position={[0, 4.73, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.99, 1, 1]}>
            <mesh geometry={nodes.defaultMaterial_35.geometry} material={nodes.defaultMaterial_35.material} />
          </group>
          <group position={[2.5, 1.31, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_36.geometry} material={nodes.defaultMaterial_36.material} />
          </group>
          <group position={[2.65, 0.49, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_37.geometry} material={nodes.defaultMaterial_37.material} />
          </group>
          <group position={[2.51, 1.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_38.geometry} material={nodes.defaultMaterial_38.material} />
          </group>
          <group position={[2.7, 3.04, 0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={1.31}>
            <mesh geometry={nodes.defaultMaterial_39.geometry} material={nodes.defaultMaterial_39.material} />
          </group>
          <group position={[0, 0.46, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_40.geometry} material={nodes.defaultMaterial_40.material} />
          </group>
          <group position={[0, 0.46, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_41.geometry} material={nodes.defaultMaterial_41.material} />
          </group>
          <group position={[2, 2.52, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_42.geometry} material={nodes.defaultMaterial_42.material} />
          </group>
          <group position={[2, 2.51, -0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.04, 1]}>
            <mesh geometry={nodes.defaultMaterial_43.geometry} material={nodes.defaultMaterial_43.material} />
          </group>
          <group position={[1.98, 0.35, -0.18]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.defaultMaterial_44.geometry} material={nodes.defaultMaterial_44.material} />
          </group>
          <group position={[1.06, 0.17, -0.17]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.defaultMaterial_45.geometry} material={nodes.defaultMaterial_45.material} />
          </group>
          <group position={[0, 0.41, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_46.geometry} material={nodes.defaultMaterial_46.material} />
          </group>
          <group position={[0, 0.46, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_47.geometry} material={nodes.defaultMaterial_47.material} />
          </group>
          <group position={[0, 0.46, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_48.geometry} material={nodes.defaultMaterial_48.material} />
          </group>
          <group position={[0, 4.58, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.19, 1.27, 1.27]}>
            <group position={[0, -16, -4.02]} scale={[1.06, 1, 1]}>
              <mesh geometry={nodes.defaultMaterial_62.geometry} material={nodes.defaultMaterial_62.material} />
            </group>
            <group position={[-0.08, -16, -4.02]} scale={[1.06, 1, 1]}>
              <mesh geometry={nodes.defaultMaterial_63.geometry} material={nodes.defaultMaterial_63.material} />
            </group>
            <mesh geometry={nodes.defaultMaterial_49.geometry} material={nodes.defaultMaterial_49.material} />
          </group>
          <group position={[2.25, 0.27, 1.09]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes.defaultMaterial_50.geometry} material={nodes.defaultMaterial_50.material} />
          </group>
          <group position={[2.25, 0.27, -1.36]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes.defaultMaterial_51.geometry} material={nodes.defaultMaterial_51.material} />
          </group>
          <group position={[3.84, 0.26, -0.12]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_52.geometry} material={nodes.defaultMaterial_52.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.97]}>
            <mesh geometry={nodes.defaultMaterial_53.geometry} material={nodes.defaultMaterial_53.material} />
          </group>
          <group position={[3, 0.46, 1.47]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_54.geometry} material={nodes.defaultMaterial_54.material} />
          </group>
          <group position={[3, 0.46, 1.05]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_55.geometry} material={nodes.defaultMaterial_55.material} />
          </group>
          <group position={[3, 0.46, 0.63]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_56.geometry} material={nodes.defaultMaterial_56.material} />
          </group>
          <group position={[3, 0.46, 0.21]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_57.geometry} material={nodes.defaultMaterial_57.material} />
          </group>
          <group position={[3, 0.46, -1.44]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_58.geometry} material={nodes.defaultMaterial_58.material} />
          </group>
          <group position={[3, 0.46, -1.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_59.geometry} material={nodes.defaultMaterial_59.material} />
          </group>
          <group position={[3, 0.46, -0.61]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_60.geometry} material={nodes.defaultMaterial_60.material} />
          </group>
          <group position={[3, 0.46, -0.2]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_61.geometry} material={nodes.defaultMaterial_61.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cottage.glb')
